### ISSUE TITLE
Week 3 - Tasks List

### ISSUE THREAD

**Issue by PhilsChan** [UBC-MDS/world-energy-visualization#23]
**Docker Deployment**
- [x] #24
- [x] #25

**Update README.md**
- [x] #26

**Comparing Technology**
- [x] Study the tech & write some description in https://github.com/UBC-MDS/dash-tableau-shiny_comparison @miyer26 

**Peer Review**
- [x] Open an Issue in https://github.com/UBC-MDS/DSCI532-peer-review @miyer26 
- [x] Persona @miyer26 
- [x] Frontend / layout @MacyChan 
- [x] Backend @PhilsChan 
- [x] Documentation @MacyChan 
- [x] Post-review improvement idea on own project @plevchen

**Comment by miyer26** [comment]
Here is the write-up for the tech study. Please feel free to add on to it before we do the final submission. Thanks! 


# Deploying a dashboard on Shinyapp.io

## Brief description
There are multiple ways to deploy a Shiny app on the web. These include deployment to the cloud through Shinyapps.io, open-source virtual private cloud through the Shiny Servers, and commercially in a premises/virtual private cloud using RStudio Connect. Shinyapps.io is a flexible and easy-to-use option to deploy apps as quickly as a few minutes that is hosted on servers operated by R Studio. Hence it is suitable for hosting prototypes, individual projects but also more complex projects. It can be used for free to host up to 5 apps, and if there is a need for more, there are tiered paid versions. The open-source Shiny server has the advantage that it can run behind private firewalls, can be used to host multiple applications using the same server, each with a unique URL. Again this version is free. The recommended option for commercial deployment is through RStudio Connect, which is a standalone product that supports both Python and R , and can host applications, dashboards, and even Jupyter Notebook. The servers it is deployed on can be controlled by the organization, whether it is on some server behind a firewall or a VPC. It also includes a whole host of other features including integration with RStudio, easy scale-up, and web application support.


## Long description
### Host a Shiny app
In general, there are two main ways to host Shiny apps on the web: through servers hosted by RStudio or on personal servers. Under personal servers, there are two versions - open source and commercial.

#### Servers hosted by RStudio
1. Shinyapps.io is a flexible and easy-to-use cloud-based option to deploy apps as quickly as a few minutes. It is a software as service package that is hosted in servers operated by R Studio. It is suitable for hosting prototypes, individual projects, and also more complex projects due to its ease of use.  It can be used for free to host up to 5 apps, and if there is a need for more, there are tiered paid versions. Scalability is also very easy as this method is cloud-based. However, the disadvantage is that there is no firewall protection for the app, so commercial or company-specific apps may not be suited for this type of deployment. 

#### Personal servers
2. The open-source Shiny Server package has the advantage that it can run behind private firewalls and can be used to host multiple applications using the same server, each with a unique URL. The professional version of Shiny Server offers additional features such as access restrictions for the applications, SSL encryption, and performance management. Shiny Server open source is free, whereas the professional version is paid.

3. The recommended option for commercial deployment is through RStudio Connect, which is a standalone product that supports both Python and R and can host applications, dashboards, and even Jupyter Notebooks. It is also integrated with Git and provides a user interface. The servers it is deployed on can be controlled by the organization, whether it is on some server behind a firewall or a VPC. It also includes a whole host of other features including integration with RStudio, easy scale-up, and web application support. It is designed to be used by many users within an organization. It is however only available as a paid version. 


### Deploy and Share a Shiny app through servers hosted by RStudio

The most common and efficient way to deploy a Shiny app is through servers hosted by RStudio. Here are the step and charges for the service.

Shiny Servers can currently only be hosted from Ubuntu 14.04+ (64 bit) or CentOS/RHEL 6+ (64 bit), or SLES 12. RStudio has provided these systems with pre-built installers. Otherwise, the server has to be built from the source, for which the instructions are listed [here](https://github.com/rstudio/shiny-server/wiki/Building-Shiny-Server-from-Source).

Once installed, Shiny resorts to deploying apps on the default configuration, in which the apps will be hosted on port 3838. To launch an app, you can copy the app into the location of the server on your PC: 
`sudo cp -R ~/MY-APP /srv/shiny-server/`

The configurations can be altered using this [reference](https://docs.rstudio.com/shiny-server/) to launch on different ports or other settings. 

- Can take the reference here

### Shiny's subscription plans

Deployment on the Shiny cloud through Shiny.io comes at different price points, and offers different features.

| | Free | Starter  | Basic | Standard | Professional |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Cost  | Free  | $9/mo | $39/mo | $99/mo | $299/mo | 
| # of Apps  | 5  | 25 | Unlimited | Unlimited | Unlimited |
| Hours  | 25  | 100 | 500 | 2000 | 10000 |


### Links
https://shiny.rstudio.com/deploy/
https://www.rstudio.com/products/shiny/download-server/
https://docs.rstudio.com/shiny-server/#introduction
https://www.rstudio.com/assets/img/RStudio-Connect-12July2021.pdf
https://shiny.rstudio.com/tutorial/written-tutorial/lesson7/
https://github.com/rstudio/shiny-server/blob/master/README.md
https://github.com/rstudio/shiny-server/wiki/Building-Shiny-Server-from-Source

**Comment by MacyChan** [comment]
Some issue to be fixed
- [x]  Should place it as favicon.ico in a folder called assets in the root of the project, currently it is not at the root. @plevchen 
- [ ] PR merge the above at [here](https://github.com/UBC-MDS/dash-tableau-shiny_comparison) @miyer26 

Comment for [dash-tableau-shiny_comparison](https://github.com/UBC-MDS/dash-tableau-shiny_comparison) will be posted separately

**Comment by MacyChan** [comment]
About the comparison,

- Missing a title (added)
- I edited some typos... it's hard to comment here so I edited them directly
- Just curious, is it `R Studio1` & `Jupyter Notebooks3`? Or are they typos?
- Are the (1)(2)(3)(4) referring to the links? if so I think it better to add short links as well, a bit confusing
- By peeking at others' work, people seem to do a bit more technical in long description. Feel like or long description has the same length as a short description. Mind adding a bit more? I have edited a skeleton, I think just copying and pasting for part of them would be good. Hope it is not too much work.

* I found some links, I guess we can just base on it and do a bit of editing for a detailed reference
https://shiny.rstudio.com/tutorial/written-tutorial/lesson7/


https://github.com/UBC-MDS/dash-tableau-shiny_comparison/blob/main/group_10.md
https://github.com/UBC-MDS/dash-tableau-shiny_comparison/blob/main/group_19.md

**Comment by PhilsChan** [comment]
> Some issue to be fixed
> 
> * [ ]   Should place it as favicon.ico in a folder called assets in the root of the project, currently it is not at the root. @plevchen
> * [ ]  PR merge the above at [here](https://github.com/UBC-MDS/dash-tableau-shiny_comparison) @miyer26
> 
> Comment for [dash-tableau-shiny_comparison](https://github.com/UBC-MDS/dash-tableau-shiny_comparison) will be posted separately

Regarding the `favicon.ico` I have tried placing the image to `assets/` at root folder, but the icon does not render as before. I guess our current location makes more sense. I saw other groups are placing the icon under `src/assets/` as well

**Comment by MacyChan** [comment]
Did some final edits and PRed
https://github.com/UBC-MDS/dash-tableau-shiny_comparison/pull/33
Seems I don’t have access to merge
